s="welcome"
for i in range (0,7,1):
	print(s[i])



s="welcome"
for i in range (0,len(s),1):
	print(s[i])



s="welcome"
for i in range (-len(s),0,1):
	print(s[i])	



#display backward
s="welcome"
for i in range (len(s)-1,-1,-1):
	print(s[i])



s="welcome"
for i in range (-1,-len(s)-1,-1):
	print(s[i])


#display individual later downward

s="welcome"
for i in range (0,len(s),1):
	print(s[i])


#reverse
s="welcome"
for i in range (len(s)-1,-1,-1):
	print(s[i])

s="welcome"
for i in range (0,7,1):
	print(s[i])



